language: rust

git:
  depth: false

dist: bionic

jobs:
  include:
    - os: linux
      env:
        - PUBLISH_DOC=true
        - PUBLISH_PACKAGE=true
        - FEATURES=--all-features
    - os: osx
      env:
        - FEATURES=--all-features
    - os: windows
      env:
        - FEATURES=--all-features
    - rust: beta
      env:
        - FEATURES=--all-features
    - rust: nightly
      env:
        - CODECOV_COVERAGE=true
        - FEATURES=--all-features
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-musl
        - FEATURES=--features=vendored
      addons:
        apt:
          update: true
          packages: musl-tools
    - os: windows
      env: TARGET=x86_64-pc-windows-msvc

before_install:
  - chmod -R 777 ci

install:
  - . ci/install.sh

before_script:
  - . ci/before_script.sh

script:
  - . ci/script.sh

deploy:
  - provider: script
    script: bash ci/create_index.sh
    skip_cleanup: true
    on:
      branch: master
      condition: $PUBLISH_DOC = true
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: "target/doc"
    committer_from_gh: true
    on:
      branch: master
      condition: $PUBLISH_DOC = true
  - provider: cargo
    token: $CARGO_TOKEN
    on:
      tags: true
      condition: $PUBLISH_PACKAGE = true
  - provider: script
    script: bash ci/codecov_coverage.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CODECOV_COVERAGE = true

notifications:
  email: false